from dataclasses import dataclass


@dataclass(frozen=True)
class SeedFAQ:
    category_name: str
    category_slug: str
    category_description: str
    question: str
    answer: str
    intent_label: str
    sort_order: int


CATEGORY_FAQ_GROUPS: list[tuple[str, str, str, list[tuple[str, str, str]]]] = [
    (
        "Foundations",
        "foundations",
        "Core ideas behind modern AI systems.",
        [
            ("What is artificial intelligence?", "Artificial intelligence is the field of building systems that can perform tasks that normally require human intelligence, such as perception, language understanding, reasoning, and decision-making.", "ai_definition"),
            ("What is machine learning?", "Machine learning is a subset of AI where models learn patterns from data instead of being explicitly programmed for every rule.", "ml_definition"),
            ("What is supervised learning?", "Supervised learning trains a model on labeled examples so it can learn the relationship between inputs and the correct outputs.", "supervised_learning"),
            ("What is unsupervised learning?", "Unsupervised learning looks for structure in unlabeled data, such as clusters, themes, or latent patterns.", "unsupervised_learning"),
            ("What is reinforcement learning?", "Reinforcement learning trains an agent through rewards and penalties as it interacts with an environment.", "reinforcement_learning"),
            ("What is a dataset?", "A dataset is a collection of examples used to train, validate, or test a model.", "dataset_definition"),
            ("Why does data quality matter?", "High-quality data helps a model learn useful patterns, while noisy or biased data can reduce accuracy and fairness.", "data_quality"),
            ("What is model inference?", "Inference is the step where a trained model makes predictions on new inputs.", "model_inference"),
            ("What is a loss function?", "A loss function measures how far a model’s prediction is from the target answer, giving training a signal to improve.", "loss_function"),
            ("What is a feature?", "A feature is an input variable or measurable property that helps a model make a prediction.", "feature_definition"),
        ],
    ),
    (
        "Deep Learning",
        "deep-learning",
        "Neural-network methods for vision, language, and more.",
        [
            ("What is deep learning?", "Deep learning uses multi-layer neural networks to learn hierarchical representations from large amounts of data.", "deep_learning_definition"),
            ("How does backpropagation work?", "Backpropagation computes how each weight contributed to the final error and uses that information to update the network.", "backpropagation"),
            ("What is an activation function?", "An activation function adds nonlinearity so a neural network can model complex relationships.", "activation_function"),
            ("Why do deep models often use GPUs?", "GPUs speed up the large matrix operations common in deep learning, which makes training much faster.", "gpu_usage"),
            ("What is a hidden layer?", "A hidden layer is an internal layer between input and output that transforms the data into useful representations.", "hidden_layer"),
            ("What is gradient descent?", "Gradient descent is an optimization method that repeatedly nudges model parameters in the direction that lowers the loss.", "gradient_descent"),
            ("What is a training epoch?", "One epoch is one full pass through the training dataset.", "training_epoch"),
            ("What is dropout?", "Dropout randomly disables some neurons during training to reduce overfitting.", "dropout"),
            ("What is batch normalization?", "Batch normalization normalizes activations during training to improve stability and speed.", "batch_normalization"),
            ("What is the vanishing gradient problem?", "The vanishing gradient problem happens when gradients become extremely small, making it hard for early layers to learn.", "vanishing_gradient"),
        ],
    ),
    (
        "Transformers",
        "transformers",
        "Attention-based models used in modern language systems.",
        [
            ("What is the transformer architecture?", "The transformer architecture is a neural network design built around self-attention, allowing a model to focus on relevant parts of an input sequence in parallel rather than step by step.", "transformer_architecture"),
            ("What is self-attention?", "Self-attention is the mechanism that lets a model measure how strongly each token should interact with other tokens in the same input, which helps it capture long-range dependencies.", "self_attention"),
            ("What is multi-head attention?", "Multi-head attention runs several attention operations in parallel so the model can learn different kinds of relationships at once.", "multi_head_attention"),
            ("What is a token?", "A token is a chunk of text, such as a word, subword, or symbol, that the model processes as an input unit.", "token_definition"),
            ("What is positional encoding?", "Positional encoding gives the model information about token order, which attention alone does not provide.", "positional_encoding"),
            ("Why are transformers parallelizable?", "Transformers process all tokens in a sequence at the same time during training, which makes them efficient on modern hardware.", "transformer_parallelism"),
            ("What is a decoder-only model?", "A decoder-only model predicts the next token from the previous context and is commonly used for text generation.", "decoder_only_model"),
            ("What is an encoder-decoder transformer?", "An encoder-decoder transformer uses one stack to read the input and another stack to generate the output, which is useful for translation and summarization.", "encoder_decoder_transformer"),
            ("What is a context window?", "The context window is the maximum amount of text the model can consider at one time.", "context_window"),
            ("What is causal masking?", "Causal masking prevents a model from looking at future tokens while it is predicting the next one.", "causal_masking"),
        ],
    ),
    (
        "Language Models",
        "language-models",
        "Generative models that predict and create text.",
        [
            ("What is a large language model?", "A large language model is a neural network trained on vast text corpora to predict tokens, enabling it to answer questions, generate content, and assist with reasoning tasks.", "llm_definition"),
            ("How do language models generate text?", "They generate text by predicting the next token repeatedly, using the previous tokens as context.", "text_generation"),
            ("What is next-token prediction?", "Next-token prediction is the training objective of learning to guess the next token in a sequence.", "next_token_prediction"),
            ("What is prompt engineering?", "Prompt engineering is the practice of designing inputs that guide a language model toward the most useful, accurate, and safe output.", "prompt_engineering"),
            ("What is instruction tuning?", "Instruction tuning trains a model on examples that pair instructions with good answers so it follows user requests more reliably.", "instruction_tuning"),
            ("What is chain-of-thought prompting?", "Chain-of-thought prompting asks a model to reason through a problem in steps before answering.", "chain_of_thought_prompting"),
            ("What is temperature in text generation?", "Temperature controls how random the model’s token choices are, with higher values producing more varied outputs.", "temperature"),
            ("What is top-k sampling?", "Top-k sampling limits the model to the k most likely next tokens before it picks one.", "top_k_sampling"),
            ("What is hallucination in an LLM?", "Hallucination is when a model produces fluent but incorrect or unsupported information.", "hallucination"),
            ("What is fine-tuning a language model?", "Fine-tuning continues training a pretrained model on a smaller task-specific dataset so it adapts to a new use case.", "language_model_fine_tuning"),
        ],
    ),
    (
        "Retrieval",
        "retrieval",
        "Retrieval-augmented systems that combine search with generation.",
        [
            ("What is retrieval augmented generation?", "Retrieval-augmented generation, or RAG, combines a search step with a generative model so responses can be grounded in external knowledge.", "rag_definition"),
            ("What is semantic search?", "Semantic search finds results based on meaning rather than exact keyword matches.", "semantic_search"),
            ("What are embeddings?", "Embeddings convert text into vectors where similar meanings end up close together, making semantic search more flexible than exact keyword matching.", "embeddings"),
            ("What is a vector database?", "A vector database stores embeddings and makes it fast to search for the nearest semantic matches.", "vector_database"),
            ("Why chunk documents for retrieval?", "Chunking breaks large documents into smaller pieces so retrieval can surface the most relevant passages.", "document_chunking"),
            ("What is reranking?", "Reranking is a second pass that reorders retrieved results using a more precise scoring method.", "reranking"),
            ("What is hybrid search?", "Hybrid search combines keyword matching with semantic search to improve recall and precision.", "hybrid_search"),
            ("What does recall mean in retrieval?", "Recall measures how many of the relevant items the system successfully found.", "retrieval_recall"),
            ("What is grounding?", "Grounding means tying a generated answer back to source material so it is easier to verify.", "grounding"),
            ("How do you evaluate retrieval?", "You evaluate retrieval with metrics such as recall, precision, hit rate, and human judgment on whether the right sources were returned.", "retrieval_evaluation"),
        ],
    ),
    (
        "Training",
        "training",
        "Practical questions about fitting and improving neural models.",
        [
            ("What is overfitting in AI?", "Overfitting happens when a model learns training data too specifically and performs poorly on unseen data.", "overfitting"),
            ("What is underfitting?", "Underfitting happens when a model is too simple or undertrained to capture the patterns in the data.", "underfitting"),
            ("What is regularization?", "Regularization adds constraints or penalties that discourage overly complex models and improve generalization.", "regularization"),
            ("What is early stopping?", "Early stopping ends training when validation performance stops improving.", "early_stopping"),
            ("What is learning rate?", "The learning rate controls how large each parameter update is during optimization.", "learning_rate"),
            ("What is batch size?", "Batch size is the number of training examples used to compute one gradient update.", "batch_size"),
            ("What is class imbalance?", "Class imbalance happens when some labels appear far more often than others, which can bias the model toward the common class.", "class_imbalance"),
            ("What is cross-validation?", "Cross-validation evaluates a model on multiple train-test splits to estimate how well it generalizes.", "cross_validation"),
            ("What is transfer learning?", "Transfer learning reuses knowledge from one task or dataset to improve performance on another task.", "transfer_learning"),
            ("What is hyperparameter tuning?", "Hyperparameter tuning is the process of searching for the training settings that give the best validation performance.", "hyperparameter_tuning"),
        ],
    ),
    (
        "Convolutional Networks",
        "cnn",
        "Vision-oriented neural networks that detect local patterns.",
        [
            ("What is a CNN?", "A convolutional neural network, or CNN, is a model designed to detect local patterns such as edges, textures, and shapes, especially in images.", "cnn_definition"),
            ("What is a convolution?", "A convolution is a sliding operation that applies a filter across input data to detect patterns.", "convolution"),
            ("What is a filter or kernel?", "A filter, or kernel, is a small learnable matrix that looks for a specific pattern in the input.", "filter_kernel"),
            ("What is pooling?", "Pooling reduces spatial size while keeping the most important information from a feature map.", "pooling"),
            ("What is a feature map?", "A feature map is the output produced when a filter responds to patterns in the input.", "feature_map"),
            ("Why do CNNs work well on images?", "CNNs work well on images because they exploit local structure and share weights across the image.", "cnn_image_advantage"),
            ("What is stride?", "Stride is how far a convolutional filter moves at each step.", "stride"),
            ("What is padding?", "Padding adds border values around an input so convolution can preserve size or better use edge information.", "padding"),
            ("What is a receptive field?", "A receptive field is the portion of the input that can influence one neuron or feature at a given layer.", "receptive_field"),
            ("What is image classification?", "Image classification is the task of assigning an image to one or more categories.", "image_classification"),
        ],
    ),
    (
        "Recurrent Networks",
        "rnn",
        "Sequence models that process information step by step.",
        [
            ("What is an RNN?", "A recurrent neural network, or RNN, processes sequences one step at a time and keeps a hidden state so earlier information can influence later predictions.", "rnn_definition"),
            ("What is a hidden state?", "A hidden state is the memory an RNN carries forward from one time step to the next.", "hidden_state"),
            ("What is sequence modeling?", "Sequence modeling is the task of learning from ordered data such as text, audio, or time series.", "sequence_modeling"),
            ("What is an LSTM?", "An LSTM is a recurrent architecture that uses gates to remember useful information for longer periods.", "lstm"),
            ("What is a GRU?", "A GRU is a simpler gated recurrent unit that helps an RNN keep track of important sequence information.", "gru"),
            ("Why do vanilla RNNs struggle with long sequences?", "Vanilla RNNs often struggle with long sequences because gradients can vanish or explode as they move through time.", "rnn_long_sequence_limitations"),
            ("What is teacher forcing?", "Teacher forcing trains sequence models by feeding the correct previous token during training instead of the model’s own prediction.", "teacher_forcing"),
            ("What is sequence-to-sequence learning?", "Sequence-to-sequence learning maps one sequence to another, such as translating text or summarizing a document.", "sequence_to_sequence"),
            ("What is time-step processing?", "Time-step processing means the model handles sequence elements one at a time in order.", "time_step_processing"),
            ("What is a bidirectional RNN?", "A bidirectional RNN reads the sequence in both directions so it can use past and future context.", "bidirectional_rnn"),
        ],
    ),
    (
        "Evaluation",
        "evaluation",
        "How to measure whether AI models are useful and reliable.",
        [
            ("How do you evaluate an AI model?", "You evaluate an AI model by measuring task-specific metrics such as accuracy, precision, recall, F1, BLEU, or human preference, depending on the use case.", "model_evaluation"),
            ("What is accuracy?", "Accuracy is the share of predictions the model got right overall.", "accuracy"),
            ("What is precision?", "Precision measures how many predicted positives were actually correct.", "precision"),
            ("What is recall?", "Recall measures how many actual positives the model found.", "recall"),
            ("What is F1 score?", "The F1 score balances precision and recall in a single number.", "f1_score"),
            ("What is ROC-AUC?", "ROC-AUC measures how well a model separates classes across different decision thresholds.", "roc_auc"),
            ("What is perplexity?", "Perplexity measures how well a language model predicts text, with lower values indicating better fit.", "perplexity"),
            ("What is human evaluation?", "Human evaluation asks people to judge whether the model’s output is correct, useful, or safe.", "human_evaluation"),
            ("What is offline evaluation?", "Offline evaluation checks a model against saved datasets before it is deployed.", "offline_evaluation"),
            ("What is a test set?", "A test set is a held-out dataset used to estimate final model performance on unseen data.", "test_set"),
        ],
    ),
    (
        "Ethics",
        "ethics",
        "Responsible AI topics such as bias, transparency, and safety.",
        [
            ("What is AI bias?", "AI bias happens when a model produces systematically unfair outcomes because of biased data, design choices, or evaluation gaps.", "ai_bias"),
            ("What is fairness in AI?", "Fairness in AI means aiming for outcomes that do not unfairly disadvantage particular people or groups.", "fairness"),
            ("What is explainable AI?", "Explainable AI refers to methods that help people understand why a model produced a particular prediction or recommendation.", "xai_definition"),
            ("What is model transparency?", "Model transparency means making model behavior, limitations, and decision factors easier for people to inspect.", "model_transparency"),
            ("What is data privacy?", "Data privacy is the practice of protecting personal information from unnecessary collection, exposure, or misuse.", "data_privacy"),
            ("What is responsible AI?", "Responsible AI is the practice of building and deploying systems with attention to fairness, safety, accountability, and privacy.", "responsible_ai"),
            ("What is harmful output?", "Harmful output is model content that could mislead, harass, discriminate, or otherwise cause harm.", "harmful_output"),
            ("What does alignment mean?", "Alignment means making a model behave in ways that match human goals, values, and instructions.", "alignment"),
            ("What is content moderation?", "Content moderation is the process of filtering or reviewing outputs to reduce unsafe or inappropriate content.", "content_moderation"),
            ("Why is human oversight important?", "Human oversight helps catch mistakes, handle edge cases, and keep AI systems accountable.", "human_oversight"),
        ],
    ),
    (
        "Safety & Alignment",
        "safety-alignment",
        "Methods for making AI systems reliable, safe, and aligned with user goals.",
        [
            ("What is AI safety?", "AI safety is the practice of reducing the chance that an AI system behaves in harmful, unreliable, or unintended ways.", "ai_safety"),
            ("What is alignment in AI?", "Alignment means making a model behave in ways that match human goals, values, and instructions.", "ai_alignment"),
            ("What is reinforcement learning from human feedback?", "Reinforcement learning from human feedback, or RLHF, uses human preferences to improve how a model responds.", "rlhf"),
            ("What is a safety policy for AI?", "A safety policy defines rules and boundaries for what the system should refuse, redirect, or handle carefully.", "safety_policy"),
            ("What is red teaming?", "Red teaming is the practice of deliberately probing a system to find failures, risks, or unsafe behaviors before deployment.", "red_teaming"),
            ("What is jailbreak resistance?", "Jailbreak resistance is a model’s ability to ignore prompts that try to bypass safety constraints.", "jailbreak_resistance"),
            ("What is prompt injection?", "Prompt injection is an attack where malicious text tries to override the model’s intended instructions.", "prompt_injection"),
            ("Why are refusal behaviors important?", "Refusal behaviors help the model decline unsafe requests and reduce harmful outputs.", "refusal_behavior"),
            ("What is model monitoring?", "Model monitoring tracks outputs and performance after deployment to catch drift, abuse, or unexpected failures.", "model_monitoring"),
            ("What is guardrailing?", "Guardrailing adds controls that steer the model toward safe, appropriate, and policy-compliant behavior.", "guardrailing"),
        ],
    ),
    (
        "ML Algorithms & Training",
        "ml-algorithms-training",
        "Core machine learning algorithms and the training process behind them.",
        [
            ("What is supervised machine learning?", "Supervised machine learning trains a model on labeled examples so it can predict outputs for new inputs.", "supervised_ml"),
            ("What is logistic regression?", "Logistic regression is a classification algorithm that estimates the probability of a class using a linear model and a sigmoid function.", "logistic_regression"),
            ("What is decision tree learning?", "Decision tree learning builds a model by splitting data into branches based on feature values.", "decision_tree_learning"),
            ("What is random forest?", "A random forest is an ensemble of decision trees whose predictions are combined to improve accuracy and stability.", "random_forest"),
            ("What is support vector machine?", "A support vector machine, or SVM, finds a boundary that best separates classes in the feature space.", "svm"),
            ("What is k-nearest neighbors?", "k-nearest neighbors predicts a label or value based on the closest training examples in feature space.", "knn"),
            ("What is naive Bayes?", "Naive Bayes is a probabilistic classifier that applies Bayes’ theorem with a simplifying independence assumption.", "naive_bayes"),
            ("What is unsupervised clustering?", "Unsupervised clustering groups similar data points together without labeled answers.", "clustering"),
            ("What is hyperparameter optimization?", "Hyperparameter optimization searches for training settings that produce the best validation performance.", "hyperparameter_optimization"),
            ("What is model convergence?", "Model convergence happens when training no longer improves the loss or validation metrics in a meaningful way.", "model_convergence"),
        ],
    ),
    (
        "Computer Vision",
        "computer-vision",
        "AI systems that interpret images and video.",
        [
            ("What is computer vision?", "Computer vision is the field of AI that helps machines interpret and analyze images, video, and other visual data.", "computer_vision_definition"),
            ("What is image classification?", "Image classification assigns one or more labels to an image based on what it contains.", "image_classification"),
            ("What is object detection?", "Object detection finds and labels objects in an image, usually with bounding boxes.", "object_detection"),
            ("What is image segmentation?", "Image segmentation divides an image into regions or pixels so the model can understand object boundaries more precisely.", "image_segmentation"),
            ("What is a bounding box?", "A bounding box is a rectangular frame used to show where an object appears in an image.", "bounding_box"),
            ("What is optical character recognition?", "Optical character recognition, or OCR, extracts text from images or scanned documents.", "ocr"),
            ("What is face recognition?", "Face recognition identifies or verifies a person from facial features in an image or video.", "face_recognition"),
            ("Why are data labels important in vision tasks?", "Labels tell the model what each image contains, which helps it learn the correct visual patterns.", "vision_labels"),
            ("What is augmentation in computer vision?", "Augmentation creates modified copies of training images, such as flips or crops, to improve robustness.", "vision_augmentation"),
            ("What is a convolutional feature extractor?", "A convolutional feature extractor is a CNN component that turns raw pixels into useful visual representations.", "vision_feature_extractor"),
        ],
    ),
    (
        "Generative AI",
        "generative-ai",
        "Models that create text, images, code, and other content.",
        [
            ("What is generative AI?", "Generative AI is a class of models that can create new content such as text, images, audio, video, or code.", "generative_ai_definition"),
            ("How is generative AI different from predictive AI?", "Predictive AI estimates labels or values, while generative AI produces new content as an output.", "generative_vs_predictive_ai"),
            ("What is text generation?", "Text generation is the process of producing new written content token by token.", "text_generation"),
            ("What is image generation?", "Image generation creates new images from prompts, noise, or reference inputs.", "image_generation"),
            ("What is a diffusion model?", "A diffusion model learns to remove noise step by step to produce an image or other sample.", "diffusion_model"),
            ("What is a generative adversarial network?", "A generative adversarial network, or GAN, uses a generator and discriminator that compete to improve sample quality.", "gan"),
            ("What is prompt conditioning?", "Prompt conditioning means steering a generative model with text or other inputs so it produces the desired result.", "prompt_conditioning"),
            ("What is content variation?", "Content variation is the ability of a generative model to produce multiple different outputs from similar prompts.", "content_variation"),
            ("What is controllable generation?", "Controllable generation lets users guide style, format, tone, or structure in the output.", "controllable_generation"),
            ("What is synthetic data generation?", "Synthetic data generation creates artificial examples that can be used to augment training or testing workflows.", "synthetic_data_generation"),
        ],
    ),
    (
        "Multimodal AI",
        "multimodal-ai",
        "Models that work across text, images, audio, and video.",
        [
            ("What is multimodal AI?", "Multimodal AI is AI that can understand or generate information across more than one data type, such as text, images, audio, or video.", "multimodal_ai_definition"),
            ("What is a multimodal model?", "A multimodal model accepts or produces multiple input and output modalities in one system.", "multimodal_model"),
            ("What is text-to-image generation?", "Text-to-image generation creates images from written prompts.", "text_to_image_generation"),
            ("What is image captioning?", "Image captioning generates a text description of an image.", "image_captioning"),
            ("What is visual question answering?", "Visual question answering answers questions about an image using both visual and language understanding.", "vqa"),
            ("What is audio understanding?", "Audio understanding is the ability to interpret speech, music, or other sounds from audio input.", "audio_understanding"),
            ("What is video understanding?", "Video understanding analyzes movement, scenes, and events across frames in a video.", "video_understanding"),
            ("What is cross-modal alignment?", "Cross-modal alignment connects related information across different modalities so the model can link them correctly.", "cross_modal_alignment"),
            ("Why is multimodal context useful?", "Multimodal context helps the model answer richer questions by combining evidence from different types of input.", "multimodal_context"),
            ("What is multimodal retrieval?", "Multimodal retrieval finds related items across different modalities, such as searching images using text.", "multimodal_retrieval"),
        ],
    ),
]


EXTRA_CATEGORY_FAQ_GROUPS: list[tuple[str, str, str, list[tuple[str, str, str]]]] = [
    (
        "Data Engineering",
        "data-engineering",
        "Preparing, cleaning, and shaping data for AI systems.",
        [
            ("What is data preprocessing?", "Data preprocessing prepares raw data so it can be used effectively for training or inference.", "data_preprocessing"),
            ("What is data cleaning?", "Data cleaning removes errors, duplicates, and inconsistent values from a dataset.", "data_cleaning"),
            ("What is feature engineering?", "Feature engineering creates useful input variables from raw data to improve model performance.", "feature_engineering"),
            ("What is data augmentation?", "Data augmentation expands a dataset by generating modified versions of existing examples.", "data_augmentation"),
            ("What is a train-validation-test split?", "A train-validation-test split separates data into sets for training, tuning, and final evaluation.", "train_validation_test_split"),
            ("Why is normalization used?", "Normalization scales values into a consistent range so models train more reliably.", "normalization"),
            ("What is missing value imputation?", "Missing value imputation fills in absent entries using a rule or estimate.", "missing_value_imputation"),
            ("What is data labeling?", "Data labeling assigns the correct target or category to each example in a dataset.", "data_labeling"),
            ("What is data drift?", "Data drift happens when the input data changes over time and no longer matches the training distribution.", "data_drift"),
            ("Why is data versioning important?", "Data versioning helps track which dataset was used for a specific model or experiment.", "data_versioning"),
        ],
    ),
    (
        "Optimization Methods",
        "optimization-methods",
        "Methods for finding better parameters and faster training.",
        [
            ("What is an objective function?", "An objective function is the quantity an optimizer tries to minimize or maximize.", "objective_function"),
            ("What is stochastic gradient descent?", "Stochastic gradient descent updates model weights using small batches of data.", "stochastic_gradient_descent"),
            ("What is momentum?", "Momentum helps optimization move more smoothly by carrying part of the previous update forward.", "momentum"),
            ("What is the Adam optimizer?", "Adam is an optimization algorithm that adapts the learning rate for each parameter.", "adam_optimizer"),
            ("What is a learning rate schedule?", "A learning rate schedule changes the learning rate during training to improve convergence.", "learning_rate_schedule"),
            ("What is gradient clipping?", "Gradient clipping limits very large gradients so training stays stable.", "gradient_clipping"),
            ("What is convex optimization?", "Convex optimization solves problems where the loss surface has a single global minimum.", "convex_optimization"),
            ("What is a local minimum?", "A local minimum is a point where the loss is lower than nearby points but not necessarily the lowest possible value.", "local_minimum"),
            ("What is batch optimization?", "Batch optimization uses the full training set or a large batch to compute each update.", "batch_optimization"),
            ("Why tune optimization settings?", "Tuning optimization settings can improve speed, stability, and final model quality.", "optimization_tuning"),
        ],
    ),
    (
        "Time Series AI",
        "time-series-ai",
        "AI for forecasting and analyzing time-ordered data.",
        [
            ("What is time series forecasting?", "Time series forecasting predicts future values from past observations ordered in time.", "time_series_forecasting"),
            ("What is seasonality?", "Seasonality is a repeating pattern that occurs at regular time intervals.", "seasonality"),
            ("What is trend in a time series?", "Trend is the long-term direction of movement in time-ordered data.", "trend"),
            ("What is a lag feature?", "A lag feature uses previous time steps as inputs for prediction.", "lag_feature"),
            ("What is anomaly detection in time series?", "Anomaly detection finds unusual values or patterns in temporal data.", "time_series_anomaly_detection"),
            ("What is a sliding window?", "A sliding window looks at a fixed chunk of earlier data to predict the next values.", "sliding_window"),
            ("What is autoregressive modeling?", "Autoregressive modeling predicts a value using previous values from the same series.", "autoregressive_modeling"),
            ("What is temporal validation?", "Temporal validation evaluates models while respecting the order of time.", "temporal_validation"),
            ("Why does order matter in time series?", "Order matters because future values should not leak into the past during training or evaluation.", "time_series_order"),
            ("What is sequence forecasting?", "Sequence forecasting predicts a future sequence rather than a single value.", "sequence_forecasting"),
        ],
    ),
    (
        "NLP Fundamentals",
        "nlp-fundamentals",
        "Core natural language processing tasks and concepts.",
        [
            ("What is tokenization?", "Tokenization breaks text into smaller units such as words or subwords.", "tokenization"),
            ("What is stemming?", "Stemming reduces words to a common root form.", "stemming"),
            ("What is lemmatization?", "Lemmatization converts words to their dictionary form.", "lemmatization"),
            ("What is named entity recognition?", "Named entity recognition finds people, places, organizations, and other named items in text.", "named_entity_recognition"),
            ("What is part-of-speech tagging?", "Part-of-speech tagging labels each word with its grammatical role.", "part_of_speech_tagging"),
            ("What is text classification?", "Text classification assigns a label to a piece of text.", "text_classification"),
            ("What is sentiment analysis?", "Sentiment analysis identifies the emotional tone of text.", "sentiment_analysis"),
            ("What is machine translation?", "Machine translation converts text from one language to another.", "machine_translation"),
            ("What is summarization?", "Summarization shortens text while preserving the main ideas.", "summarization"),
            ("What is question answering?", "Question answering returns an answer to a user’s question from text or knowledge.", "question_answering"),
        ],
    ),
    (
        "Speech AI",
        "speech-ai",
        "Models that understand and generate spoken language.",
        [
            ("What is speech recognition?", "Speech recognition converts spoken audio into text.", "speech_recognition"),
            ("What is text-to-speech?", "Text-to-speech converts written text into spoken audio.", "text_to_speech"),
            ("What is speaker diarization?", "Speaker diarization identifies who spoke and when in an audio recording.", "speaker_diarization"),
            ("What is keyword spotting?", "Keyword spotting detects specific words or phrases in audio.", "keyword_spotting"),
            ("What is an acoustic model?", "An acoustic model maps audio signals to likely speech units.", "acoustic_model"),
            ("What is a phoneme?", "A phoneme is a basic sound unit that distinguishes words.", "phoneme"),
            ("What is voice activity detection?", "Voice activity detection determines whether speech is present in an audio segment.", "voice_activity_detection"),
            ("What is speech synthesis?", "Speech synthesis generates spoken audio from text or other inputs.", "speech_synthesis"),
            ("What is audio denoising?", "Audio denoising removes background noise from an audio signal.", "audio_denoising"),
            ("Why is audio context important?", "Audio context helps the model distinguish speech from noise and understand meaning more accurately.", "audio_context"),
        ],
    ),
    (
        "AI Agents",
        "ai-agents",
        "Systems that plan, act, and use tools to complete tasks.",
        [
            ("What is an AI agent?", "An AI agent is a system that observes, plans, and acts to complete a task.", "ai_agent"),
            ("What is planning in agents?", "Planning is deciding the steps needed to reach a goal.", "agent_planning"),
            ("What is tool use?", "Tool use lets an agent call external functions or systems to get work done.", "agent_tool_use"),
            ("What is memory in agents?", "Memory lets an agent store useful information across steps or sessions.", "agent_memory"),
            ("What is reflection in agents?", "Reflection is the process of reviewing results and improving future actions.", "agent_reflection"),
            ("What is autonomous task execution?", "Autonomous task execution means the agent can carry out work with limited human intervention.", "autonomous_task_execution"),
            ("What is multi-agent collaboration?", "Multi-agent collaboration happens when several agents work together on related goals.", "multi_agent_collaboration"),
            ("What is environment observation?", "Environment observation is collecting information about the current state before acting.", "environment_observation"),
            ("What is action selection?", "Action selection chooses the next step the agent should take.", "action_selection"),
            ("Why do agents need guardrails?", "Guardrails keep agents safe, predictable, and aligned with user intent.", "agent_guardrails"),
        ],
    ),
    (
        "MLOps",
        "mlops",
        "Practices for deploying and operating machine learning systems.",
        [
            ("What is MLOps?", "MLOps combines machine learning, software engineering, and operations practices.", "mlops"),
            ("What is a model registry?", "A model registry stores and tracks model versions ready for deployment.", "model_registry"),
            ("What is CI/CD for ML?", "CI/CD for ML automates testing, validation, and deployment of machine learning systems.", "ml_ci_cd"),
            ("What is model monitoring?", "Model monitoring tracks quality, drift, and usage after deployment.", "model_monitoring"),
            ("What is a feature store?", "A feature store manages reusable features for training and serving.", "feature_store"),
            ("What is reproducibility?", "Reproducibility means being able to get the same results again under the same conditions.", "reproducibility"),
            ("What is rollback?", "Rollback returns a deployed model to a previous version if a problem appears.", "rollback"),
            ("What is a deployment pipeline?", "A deployment pipeline automates the path from trained model to production.", "deployment_pipeline"),
            ("What is a canary release?", "A canary release sends a new model to a small fraction of traffic first.", "canary_release"),
            ("Why is observability important?", "Observability helps you understand system behavior and catch production issues early.", "observability"),
        ],
    ),
    (
        "Knowledge Graphs",
        "knowledge-graphs",
        "Structured graphs that connect entities and relationships.",
        [
            ("What is a knowledge graph?", "A knowledge graph stores entities and the relationships between them.", "knowledge_graph"),
            ("What is an entity?", "An entity is a real-world object or concept represented in the graph.", "entity"),
            ("What is a relation?", "A relation connects two entities with a meaningful link.", "relation"),
            ("What is entity linking?", "Entity linking maps mentions in text to the correct graph entity.", "entity_linking"),
            ("What is ontology?", "An ontology defines the types, properties, and relations used in a knowledge domain.", "ontology"),
            ("What is graph querying?", "Graph querying asks structured questions over graph data.", "graph_querying"),
            ("What is graph embedding?", "Graph embedding turns nodes or subgraphs into vectors for machine learning.", "graph_embedding"),
            ("What is semantic reasoning?", "Semantic reasoning infers new facts from existing graph structure and meaning.", "semantic_reasoning"),
            ("What is graph completion?", "Graph completion predicts missing nodes or relations in the graph.", "graph_completion"),
            ("Why use knowledge graphs in AI?", "Knowledge graphs help AI systems organize facts and connect related concepts.", "knowledge_graph_usage"),
        ],
    ),
    (
        "Recommender Systems",
        "recommender-systems",
        "Systems that personalize content, products, or suggestions.",
        [
            ("What is collaborative filtering?", "Collaborative filtering recommends items using patterns from similar users or items.", "collaborative_filtering"),
            ("What is content-based filtering?", "Content-based filtering recommends items similar to what a user already liked.", "content_based_filtering"),
            ("What is ranking?", "Ranking orders items so the most relevant ones appear first.", "ranking"),
            ("What is cold start?", "Cold start is the difficulty of recommending well when there is little history.", "cold_start"),
            ("What is explicit feedback?", "Explicit feedback is a direct rating or review from a user.", "explicit_feedback"),
            ("What is implicit feedback?", "Implicit feedback comes from user behavior such as clicks, views, or purchases.", "implicit_feedback"),
            ("What is personalization?", "Personalization adapts recommendations to each user’s preferences.", "personalization"),
            ("What is diversity in recommendations?", "Diversity ensures recommendations are not too repetitive or narrow.", "recommendation_diversity"),
            ("What is recall in recommendation?", "Recall measures how many relevant items the recommender was able to surface.", "recommendation_recall"),
            ("Why do recommenders need feedback loops?", "Feedback loops help recommenders improve from new interaction data.", "recommendation_feedback_loop"),
        ],
    ),
    (
        "Probabilistic Modeling",
        "probabilistic-modeling",
        "Using probability to represent uncertainty and make predictions.",
        [
            ("What is a probability distribution?", "A probability distribution describes how likely different outcomes are.", "probability_distribution"),
            ("What is Bayesian inference?", "Bayesian inference updates beliefs using new evidence.", "bayesian_inference"),
            ("What is a prior?", "A prior is the initial belief before observing data.", "prior"),
            ("What is a posterior?", "A posterior is the updated belief after seeing data.", "posterior"),
            ("What is likelihood?", "Likelihood measures how well a model explains observed data.", "likelihood"),
            ("What is uncertainty estimation?", "Uncertainty estimation tells how confident a model should be in its output.", "uncertainty_estimation"),
            ("What is a latent variable?", "A latent variable is hidden structure that influences observed data.", "latent_variable"),
            ("What is the Markov assumption?", "The Markov assumption says the present state depends only on a limited past context.", "markov_assumption"),
            ("What is a generative probabilistic model?", "A generative probabilistic model explains how data could have been produced.", "generative_probabilistic_model"),
            ("Why use probabilistic models?", "Probabilistic models are useful when uncertainty matters.", "probabilistic_model_usage"),
        ],
    ),
    (
        "Model Deployment",
        "model-deployment",
        "Serving models reliably in real applications.",
        [
            ("What is model serving?", "Model serving makes a trained model available to applications through an interface.", "model_serving"),
            ("What is latency?", "Latency is the time it takes to produce a prediction.", "latency"),
            ("What is throughput?", "Throughput is how many requests a model can process in a period of time.", "throughput"),
            ("What is scalability?", "Scalability is the ability to handle more traffic or larger workloads.", "scalability"),
            ("What is load balancing?", "Load balancing spreads requests across servers so no single server is overloaded.", "load_balancing"),
            ("What is caching?", "Caching stores repeated results so they can be returned faster next time.", "caching"),
            ("What is A/B testing?", "A/B testing compares two model or system versions to see which performs better.", "ab_testing"),
            ("What is blue-green deployment?", "Blue-green deployment switches traffic from one live version to another with minimal downtime.", "blue_green_deployment"),
            ("What is shadow deployment?", "Shadow deployment sends live traffic to a new model without affecting the user response.", "shadow_deployment"),
            ("Why monitor production models?", "Production monitoring helps catch failures, drift, and quality issues quickly.", "production_monitoring"),
        ],
    ),
    (
        "Prompt Engineering",
        "prompt-engineering-advanced",
        "Designing prompts that guide language models more effectively.",
        [
            ("What is zero-shot prompting?", "Zero-shot prompting asks the model to solve a task without examples.", "zero_shot_prompting"),
            ("What is few-shot prompting?", "Few-shot prompting includes a few examples to guide the model’s response.", "few_shot_prompting"),
            ("What is role prompting?", "Role prompting tells the model to respond as a specific type of expert or persona.", "role_prompting"),
            ("What is output formatting?", "Output formatting specifies how the response should be structured.", "output_formatting"),
            ("What is constraint prompting?", "Constraint prompting limits what the model should include or avoid.", "constraint_prompting"),
            ("What is a prompt template?", "A prompt template is a reusable prompt structure with placeholders.", "prompt_template"),
            ("What is iterative prompting?", "Iterative prompting improves output through multiple prompt revisions.", "iterative_prompting"),
            ("Why does prompt context matter?", "Prompt context matters because the model uses it to infer the task and answer style.", "prompt_context"),
            ("What is instruction hierarchy?", "Instruction hierarchy is the ordering of system, developer, and user instructions.", "instruction_hierarchy"),
            ("What is prompt testing?", "Prompt testing checks how prompts behave on different inputs before deployment.", "prompt_testing"),
        ],
    ),
    (
        "AI Evaluation Metrics",
        "ai-evaluation-metrics",
        "Common metrics for measuring model quality.",
        [
            ("What is accuracy?", "Accuracy is the fraction of predictions that were correct.", "metric_accuracy"),
            ("What is precision?", "Precision measures how many predicted positives were actually correct.", "metric_precision"),
            ("What is recall?", "Recall measures how many actual positives were found.", "metric_recall"),
            ("What is F1 score?", "F1 score balances precision and recall.", "metric_f1"),
            ("What is BLEU?", "BLEU evaluates overlap between generated text and reference text.", "metric_bleu"),
            ("What is ROUGE?", "ROUGE measures overlap between summaries or generated text and reference text.", "metric_rouge"),
            ("What is AUC?", "AUC measures how well a classifier separates classes across thresholds.", "metric_auc"),
            ("What is perplexity?", "Perplexity measures how surprised a language model is by the text it predicts.", "metric_perplexity"),
            ("What is human evaluation?", "Human evaluation asks people to judge quality, usefulness, or safety.", "metric_human_evaluation"),
            ("Why choose task-specific metrics?", "Task-specific metrics reflect what matters most for the problem being solved.", "metric_task_specific"),
        ],
    ),
    (
        "Search & Ranking",
        "search-ranking",
        "Finding, ordering, and reordering relevant content.",
        [
            ("What is lexical search?", "Lexical search matches words or phrases in the query and documents.", "lexical_search"),
            ("What is BM25?", "BM25 is a ranking method for keyword search.", "bm25"),
            ("What is query expansion?", "Query expansion adds related terms to improve search coverage.", "query_expansion"),
            ("What is candidate generation?", "Candidate generation creates a short list of likely relevant results.", "candidate_generation"),
            ("What is reranking?", "Reranking reorders a short list using a more precise model.", "reranking_search"),
            ("What is precision at k?", "Precision at k measures how many of the top k results are relevant.", "precision_at_k"),
            ("What is recall at k?", "Recall at k measures how many relevant items appear in the top k results.", "recall_at_k"),
            ("What is rank fusion?", "Rank fusion combines multiple ranking signals into one final order.", "rank_fusion"),
            ("What is relevance feedback?", "Relevance feedback uses user judgments to improve future search results.", "relevance_feedback"),
            ("Why combine search signals?", "Combining search signals improves robustness and relevance.", "search_signal_combination"),
        ],
    ),
    (
        "RAG Systems",
        "rag-systems",
        "Retrieval-augmented generation patterns and practices.",
        [
            ("What is RAG?", "Retrieval-augmented generation combines retrieval with generation so answers can use external knowledge.", "rag"),
            ("Why chunk documents in RAG?", "Chunking helps RAG retrieve the most relevant passages from larger documents.", "rag_chunking"),
            ("What is a retriever in RAG?", "The retriever finds likely source passages for the model to use.", "rag_retriever"),
            ("What is grounding in RAG?", "Grounding keeps the generated answer tied to retrieved sources.", "rag_grounding"),
            ("What is a context window in RAG?", "The context window limits how much retrieved text can fit into the prompt.", "rag_context_window"),
            ("What is hybrid retrieval in RAG?", "Hybrid retrieval combines keyword and semantic search for better recall.", "rag_hybrid_retrieval"),
            ("What is citation in RAG?", "Citation shows which retrieved source supported the answer.", "rag_citation"),
            ("How does RAG reduce hallucination?", "RAG can reduce hallucination by grounding answers in retrieved evidence.", "rag_hallucination_reduction"),
            ("What is reranking in RAG?", "Reranking improves the order of retrieved passages before generation.", "rag_reranking"),
            ("Why use RAG for generalization?", "RAG improves generalization by letting the model consult a broader knowledge base at answer time.", "rag_generalization"),
        ],
    ),
    (
        "Responsible Deployment",
        "responsible-deployment",
        "Policies and practices for safer real-world AI use.",
        [
            ("What is privacy by design?", "Privacy by design means building privacy protections into the system from the start.", "privacy_by_design"),
            ("What is consent?", "Consent means users agree to how their data will be used.", "consent"),
            ("What is a bias audit?", "A bias audit checks whether a system behaves unfairly for different groups.", "bias_audit"),
            ("What is accessibility in AI?", "Accessibility means the system can be used by people with different abilities.", "accessibility"),
            ("What is explainability?", "Explainability helps people understand how and why a model produced its output.", "deployment_explainability"),
            ("What is human-in-the-loop?", "Human-in-the-loop keeps a person involved in important decisions or reviews.", "human_in_the_loop"),
            ("What is data minimization?", "Data minimization means collecting only the data that is needed.", "data_minimization"),
            ("What is content filtering?", "Content filtering blocks or reviews unsafe or unwanted outputs.", "content_filtering"),
            ("What is policy enforcement?", "Policy enforcement applies rules consistently in the system.", "policy_enforcement"),
            ("Why is accountability important?", "Accountability makes it clear who is responsible for the system’s behavior.", "accountability"),
        ],
    ),
]


CATEGORY_FAQ_GROUPS.extend(EXTRA_CATEGORY_FAQ_GROUPS)


SEED_FAQS: list[SeedFAQ] = []
sort_order = 1
for category_name, category_slug, category_description, questions in CATEGORY_FAQ_GROUPS:
    for question, answer, intent_label in questions:
        SEED_FAQS.append(
            SeedFAQ(
                category_name=category_name,
                category_slug=category_slug,
                category_description=category_description,
                question=question,
                answer=answer,
                intent_label=intent_label,
                sort_order=sort_order,
            )
        )
        sort_order += 1
